//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MedCords.rc
//
#define IDM_ABOUTBOX                    0x0010  
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MEDCORDS_DIALOG             102
#define IDD_PersonSearch                102
#define IDD_PERSON_SEARCH               102
#define IDS_DSN                         102
#define IDSSN                           102
#define IDS_T_ID                        102
#define IDS_DATABASE                    103
#define IDS_T_BASE_LOC                  103
#define IDS_USER                        104
#define IDS_USERNAME                    104
#define IDS_PASSWORD                    105
#define IDS_DRIVER                      106
#define IDS_DOMAIN                      106
#define IDS_FILE                        107
#define IDS_TC_ID                       107
#define IDS_P_ID                        108
#define IDS_P_FULLNAME                  109
#define IDS_P_AGE                       110
#define IDS_P_GENDER                    111
#define IDS_P_DOB                       112
#define IDS_SL_NO                       113
#define IDS_E_ID                        114
#define IDS_E_TYPE                      115
#define IDS_E_STATUS                    116
#define IDS_E_DETAILS                   117
#define IDS_T_DETAILS                   118
#define IDS_O_DETAILS                   119
#define IDS_TC_GROUP                    120
#define IDS_TC_DATE                     121
#define IDS_TCO_DATE                    122
#define IDS_O_ID                        123
#define IDS_O_NAME                      124
#define IDS_O_STATUS                    125
#define IDS_O_CATALOG                   126
#define IDS_O_CATALOG_TYPE              127
#define IDR_MAINFRAME                   128
#define IDS_O_DATE                      128
#define IDS_STRING_NOPEOPLE             129
#define IDD_DIALOG1                     130
#define IDD_PERSON_DETAILS              130
#define IDD_PATIENT_DETAILS             130
#define IDS_STRING_SELECT_PAT           130
#define IDS_STRING_WRONG_CHAR           131
#define IDS_STRING_START_APP            132
#define IDS_STRING_START_TASK           133
#define IDD_ENC_DETAILS_DLG             134
#define IDS_STRING_STATUS_DATA          134
#define IDS_STRING_STATUS               135
#define IDD_IDD_TRAC_DETAILS_DLG        136
#define IDD_TRAC_DETAILS_DLG            136
#define IDS_STRING_REQ_QUAL             136
#define IDS_STRING_REQ_FN               137
#define IDD_ORD_DETAILS_DLG             138
#define IDS_STRING_REQ_LN               138
#define ID_APP_ID                       139 
#define ID_TASK_ID                      140
#define ID_REQUEST_ID                   141
#define IDS_STRING_EMPTY                142
#define IDS_STRING_WELCOME              142
#define IDS_STRING_SPACE                143
#define IDS_STRING_NOT_CI               144
#define IDS_STRING_NOT_CO               145
#define IDS_STRING_EMPTY_DATE           146
#define IDC_EDIT1_FirstName             1000
#define IDC_EDIT2                       1001
#define IDC_EDIT2_LastName              1001
#define IDC_EDIT2_StreetAddr            1001
#define IDC_EDIT2_E_TYPE                1001
#define _EnterFirstName                 1002
#define IDC_EDIT4_FirstName             1002
#define IDC_STATIC_EnterFirstName       1002
#define IDC_STATIC_EnterLastName        1003
#define IDC_EDIT4_PersonID              1003
#define IDC_EDIT1_FullNameWelcome       1004
#define IDC_EDIT3_City                  1006
#define IDC_EDIT5_LastName              1007
#define IDC_EDIT6_Country               1008
#define IDC_EDIT7_ZipCode               1009
#define IDC_EDIT9_Age                   1010
#define IDC_EDIT10_Gender               1011
#define IDC_LIST_SelectPersonList       1013
#define IDC_EDIT8_State                 1014
#define IDC_LIST_SelectPersonList2      1014
#define IDC_EDIT11_DOB                  1015
#define IDC_LIST2                       1019
#define IDC_LIST3                       1020
#define IDC_SelectPerson                1021
#define IDC_BUTTON_Search               1022
#define IDC_BUTTON2_Reset               1023
#define IDC_BUTTON_Reset                1023
#define IDC_TAB1                        1024
#define IDC_STATIC_group                1038
#define IDC_STATIC_E_ID                 1039
#define IDC_STATIC_E_TYPE               1040
#define IDC_STATIC_E_STATUS             1041
#define IDC_STATIC_E_REASON             1042
#define IDC_STATIC_E_REG_DATE           1043
#define IDC_STATIC_E_DISCH_DATE         1044
#define IDC_STATIC_E_FACILITY           1045
#define IDC_STATIC_E_BUILDING           1046
#define IDC_STATIC_NURSE_UNIT           1047
#define IDC_STATIC_E_ROOM               1048
#define IDC_STATIC_E_BED                1049
#define IDC_EDIT1                       1051
#define IDC_EDIT3_E_STATUS              1052
#define IDC_EDIT4_E_REASON              1053
#define IDC_EDIT5_E_REG_DATE            1054
#define IDC_EDIT6_E_DISCH__DATE         1055
#define IDC_EDIT7_E_FACILITY            1056
#define IDC_EDIT8_E_BUILDING            1057
#define IDC_EDIT9_E_NURSE_UNIT          1058
#define IDC_EDIT11_E_ROOM               1060
#define IDC_EDIT12                      1061
#define IDC_EDIT12_E_BED                1061
#define IDC_LIST1                       1062
#define IDC_LIST_TRACKING_LIST          1062
#define IDC_STATIC_FN_MESSAGE           1063
#define IDC_STATIC_LN_MESSAGE           1064

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
